name: Java with Gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./TechProgTZ2/gradlew
      - name: Build with Gradle
        run: ./TechProgTZ2/gradlew -p ./TechProgTZ2 build
      - name: Notify Telegram on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Build Failed
            *Repository*: ${{ github.repository }}
            *Actor*: ${{ github.actor }}
            *Commit*: ${{ github.sha }}
            *Message*: ${{ github.event.head_commit.message }}
            [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
      - name: Notify Telegram on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Тесты выполнены успешно
            *Repository*: ${{ github.repository }}
            *Actor*: ${{ github.actor }}
            *Commit*: ${{ github.sha }}
            *Message*: ${{ github.event.head_commit.message }}
            [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
